name: update-version

run-name: ${{ github.actor }} is updating version.txt for latest release

on:
   # Triggers the workflow on release
  release:
    types: [released]
  workflow_dispatch: # Allow manual trigger workflows

jobs:
  fetch:
    name: Fetch Latest Release
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.fetch-latest-release.outputs.tag_name }}
    steps:
      - uses: CityOfLosAngeles/fetch-latest-github-release@v2.0.3
        id: fetch-latest-release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
   
  update-release:
    name: Update Relase Version File
    runs-on: ubuntu-latest
    needs: fetch
    steps:
      - uses: actions/checkout@v3
      - name: "Find env"
        run: |
          set | grep GITHUB_ | grep -v GITHUB_TOKEN
          zip -r pkg.zip *.txt
          
      - uses: Radioh/action-content-overwrite@v1.0
        with:
          filePath: "${{ github.workspace }}/version.txt"
          content: '${{ needs.fetch.outputs.tag_name }}'
          
      - uses: xresloader/upload-to-github-release@v1
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
         file: "${{ github.workspace }}/version.txt;"
         update_latest_release: true
         overwrite: true
         
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
         file_pattern: '*.txt'
